# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: preparing
        uses: actions/checkout@v4
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
      - name: Check Flutter Version && Fetch Dependencies
        run: |
          cd my_app
          flutter --version
          pwd
#      - name: Build A Release APK
#        run: flutter build apk --release
