name: Manual trigger example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "One…"

  two:
    needs: one
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}     # only run this job on manual dispatch
    steps:
      - run: echo "Two…"
